### ISSUE TITLE
New package name

### ISSUE THREAD

**Issue by jesobreira** [logicalparadox/electron#15]
What's the new package name after `electron` has been given to atom-shell?

**Comment by bitsnaps** [comment]
I don't think is package lives in npm space, since `electron` now belong to the official distributed package for the [prebuild electron framework](https://www.electronjs.org/blog/npm-install-electron#the-prebuilt-electron-binary), many thanks for Luke @logicalparadox for giving this name in favor of js community world.

**Comment by logicalparadox** [comment]
As noted, it does not exist in npm space anymore. There are plenty of packages that provide similar functionality. 

I've added "DEPRECIATED" to the description.
